import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
let reqSeen = null, failSeen = null
p.on('request', r => { if (r.url().includes('web3forms')) reqSeen = r.url() })
p.on('requestfailed', r => { if (r.url().includes('web3forms')) failSeen = r.url()+' :: '+(r.failure()?.errorText) })
await p.goto('http://localhost:4173/projects', { waitUntil: 'networkidle' })
await p.evaluate(() => window.dispatchEvent(new Event('pm:feedback-open')))
await p.waitForSelector('[role=dialog]')
await p.fill('[role=dialog] input[type=text]', 'Browser test')
await p.fill('[role=dialog] input[type=email]', 'prachimittaldesign@gmail.com')
await p.fill('[role=dialog] textarea', 'test')
await p.waitForFunction(() => { const b = document.querySelector('[role=dialog] button[type=submit]'); return b && !b.disabled })
await p.click('[role=dialog] button[type=submit]')
await p.waitForTimeout(3000)
console.log('request attempted to web3forms:', reqSeen || 'NONE')
console.log('request failure:', failSeen || 'none')
const url = p.url()
console.log('page url after submit (mailto? = key not read):', url.slice(0,40))
await b.close()
